### ISSUE TITLE
Add `CONTRIBUTING` file as required by the Technical Charter

### ISSUE THREAD

**Issue by idunbarh** [SBOMit/specification#16]
As outlined in the Technical Charter document, there is a need for a `CONTRIBUTING` file that points to the [MAINTAINERS.md](https://github.com/SBOMit/specification/blob/main/MAINTAINERS.md) file. It should also include generate contribution files.

**Comment by tannerjones4075** [comment]
Hello, I would like to help with this issue.

**Comment by tannerjones4075** [comment]
Great! Can you expand on, "It should also include generate contribution files."?

**Comment by jkjell** [comment]
@tannerjones4075 here's an [example](https://github.com/in-toto/witness/blob/main/CONTRIBUTING.md) from in-toto/witness. It's a bit different for this repo as a specification but, a place to start.

**Comment by tannerjones4075** [comment]
This issue should be [closed](https://github.com/SBOMit/specification/pull/22).
