### ISSUE TITLE
Creation of SBOMit Logo

### ISSUE THREAD

**Issue by idunbarh** [SBOMit/specification#6]
Creation of a SBOMit logo thats in line with OpenSSF and CNCF guidelines (thinking phippy and friends).
- Ideas captured on [#SBOMit](https://openssf.slack.com/archives/C04U3BHL0AE/p1680104098950869) OpenSSF Slack Channel.

We have a member of the Hoppr team who is a graphic artist is going to help with creation.

**Comment by SarahLafrinere** [comment]
[SBOMit_v2.pdf](https://github.com/SBOMit/specification/files/11334586/SBOMit_v2.pdf)

**Comment by JustinCappos** [comment]
Very nice!

I think I like the quill ones the best but they are all good.

Can we make the spelling be: SBOMit (lowercase it)?

**Comment by SarahLafrinere** [comment]
> 

Yes we can make it lowercase. Easy fix

**Comment by SarahLafrinere** [comment]
SBOMit Revisions are here! Accessories have been condensed and style has changed a bit. Check it out! 
![SBOMit Option_V4-02](https://github.com/SBOMit/specification/assets/131894234/75d469c9-8775-4ebe-9840-bce71997ebe6)

**Comment by hythloda** [comment]
This logo is fantastic! Ready for submission for #15?

**Comment by JustinCappos** [comment]
> SBOMit Revisions are here! Accessories have been condensed and style has changed a bit. Check it out! ![SBOMit Option_V4-02](https://user-images.githubusercontent.com/131894234/237784896-75d469c9-8775-4ebe-9840-bce71997ebe6.png)

This one is nice, but I do think we want the writing to look like SBOMit (lowercase it).  The items you did here are great!  [SBOMit_v2.pdf](https://github.com/SBOMit/specification/files/11334812/SBOMit_v2.pdf)
